### ISSUE TITLE
iZIP compatibility 

### ISSUE THREAD

**Issue by ytcs** [ucbpylegroup/RQpy#170]
I'm having problem loading iZIP data from SLAC test site using RQpy.

For example when loading the latest series in:

```
/gpfs/slac/staas/fs1/g/supercdms/data/CDMS/SLAC/R82/Raw/09201207_151127/
```

by calling

```python
io.get_traces_midgz(filelist, ['QIS1','QOS1','QIS2','QOS2'], ['Z2','Z2','Z2','Z2'], ...)
```

The following error is produced:

```python
[...] in get_traces_midgz(path, channels, det, convtoamps, lgcskip_empty, lgcreturndict)
    383 
    384     if len(set(dets))==1:
--> 385         if channels != events[det[0]]["pChan"]:
    386             chans = [events[det[0]]["pChan"].index(ch) for ch in channels]
    387             x = events[det[0]]["p"][:, chans].astype(float)

KeyError: 'pChan'
```

**Comment by serfass** [comment]
I am not sure RQpy was ever meant to process charge channels and it seems to be looking for phonon channel names "pChan" rather than "qChan".  What type of information do you need?  Are you looking to have charge energy quantities? You could process with cdmsbats for OF charge RQs.

**Comment by slwatkins** [comment]
As Bruno said, we have never looked at charge data with RQpy, so I'm not surprised that it failed when you tried to do so. However, I would think that, if all you wanted was to open the data with this function, it would be pretty simple. In all of the dictionary calls, we would just need to add options that are equivalent, but with `'q'`s instead of `'p'`s.

I'm not sure how the processing stuff would work out though if we added charge readout functionality to the IO functions - what RQpy features are you planning to use?

**Comment by ytcs** [comment]
Ah, I see. I only need the IO functionalities from RQpy at this moment. Basically I want to reuse some of my code for phonon PSDs to do charge PSDs for testing at SLAC. I can probably make do with just using rawio but RQpy's interface is nicer + I don't need to rewrite as much code.

**Comment by slwatkins** [comment]
@ytcs I just created a branch `feature/charge_io`, where I added a boolean argument `get_charge`, where `False` gives the phonon channels, and `True` gives the charge channels. It doesn't support outputting both (since they generally don't have the same trace lengths, and that would probably get confusing anyways). But, it should work for the code you wrote!

Do you want to try it out and report back? I could also update `getrandevents` in the same way, if you think you'd use that function too.

**Comment by slwatkins** [comment]
To be specific, I was able to get the below code to run:

```python
filelist = '/gpfs/slac/staas/fs1/g/supercdms/data/CDMS/SLAC/R82/Raw/09201207_151127/09201207_151127_F0001.mid.gz'
out = rp.io.get_traces_midgz(filelist, 
    ['QIS1','QOS1','QIS2','QOS2'],
    ['Z2','Z2','Z2','Z2'],
    convtoamps=1,
    get_charge=True,
)

```

**Comment by ytcs** [comment]
Thanks! It would be great if the new branch can look for rawio instead of scdmsPyTools since I don't have scdmsPyTools in my local setup. I works on the cluster though.

**Comment by slwatkins** [comment]
Ah, that's my bad - I copied and pasted code without thinking too hard. Should be good now!

**Comment by slwatkins** [comment]
@ytcs Just checking, have you been able to try out this code?

**Comment by ytcs** [comment]
My bad. Yes, it works. Closing this issue.

**Comment by slwatkins** [comment]
No worries! Do you want me to merge the new I/O functionality to master?

**Comment by ytcs** [comment]
That'd be great. Thanks!
