### ISSUE TITLE
Add calculation of absorbed energy RQ to processing

### ISSUE THREAD

**Issue by cwfink** [ucbpylegroup/RQpy#36]
We should add the option to add an absorbed energy RQ using ```qetpy.utils.integrate_powertrace_simple```

**Comment by cwfink** [comment]
This would require the addition of an ```offset``` attribute to the RQ setup class

**Comment by slwatkins** [comment]
This can now be added, since QETpy was updated in https://github.com/ucbpylegroup/QETpy/pull/26.

@cwfink Do you think this would only generally be calculated on one channel? I can make it so that the values needed to calculate the absorbed energy RQ are set for each channel, but I feel that this is only specifically known for a couple of channels (if not just one).

**Comment by slwatkins** [comment]
@cwfink Actually, I have an idea on how to deal with this. I'll allow the power integral to be calculated only for certain channels.

**Comment by slwatkins** [comment]
@cwfink The branch `enhancement/energy_absorbed` currently supports `qetpy.utils.integrate_powertrace_simple`, but we should wait until Issue https://github.com/ucbpylegroup/QETpy/issues/29 is resolved. After which, we should update the code to be compatible with the new version of `integrate_powertrace_simple`.

**Comment by cwfink** [comment]
Fixed with PR https://github.com/ucbpylegroup/RQpy/pull/41. Closing
