### ISSUE TITLE
Add downsampled trace/psd for calculation of downsampled RQs

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/RQpy#4]
We need to add a calculation of the downsampled trace/template/RQs to the processing. This will allow us to compare an offline version of the triggering to the FIR filter trigger that was used to "tag" the event.

**Comment by cwfink** [comment]
Added our existing down sampling/truncation function to core/_pulse.py. https://github.com/berkeleycdms/RQpy/commit/f9357af50490f5c82bfe562c6565e9979ea18a22
There was mention that it should be updated/changed?

**Comment by cwfink** [comment]
@slwatkins  Was this added with the addition of truncated traces to RQ's?

If not, should this even be a feature in the standard processing? Since the user will need to provide a downsampled psd anyway, it seems like they should just redo the processing separately anyway.

Should we close this issue?

**Comment by slwatkins** [comment]
Yeah, I agree. Let's close this issue.
